
spring:
  dubbo:
    application:
     name: cosumer
    registry:
     address: zookeeper://10.25.8.39:2183,10.25.8.43:2181,10.47.69.89:2181
    scan: com.fdc.active.service
#db
  datasource:
    name: mydb
    url: jdbc:mysql://rdslzw5c801obtap9sdo.mysql.rds.aliyuncs.com:3306/base_house_wh_pre
    username: bbsadmin
    password: YiFang_2015
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 10
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20



dubbo:
  version: pre1.0.0





