
spring:
  dubbo:
    consumer:
      client: netty4
    application:
     name: cosumer
    registry:
     address: zookeeper://192.168.1.165:2181
    scan: com.fdc.active.service


#db
  datasource:
    name: mydb
    url: jdbc:mysql://192.168.1.189:3306/home_workstation_test
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    sentinel:
      master: mymaster
      nodes: 192.168.1.189:26381,192.168.1.189:26382,192.168.1.189:26383

  jpa:
    hibernate:
      ddl-auto: none #jdbc 取消hibernate





