server:
  port: 8588
  servlet:
    context-path: /activeboot
logging:
  config: classpath:logback.xml
  level:
    org.springframework.web: debug
spring:
  profiles:
    active: test

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fdc.active.domain

esearch:
  field: id,currentFloorNum,totalFloorNum,floorTypeDesc

hello:
  service:
    version: test1.0.0





